global:
  scrape_interval: 15s # How often to poll the app

scrape_configs:
  - job_name: 'campaign-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # This points to your local Spring app